SET LINESIZE 90
SET PAGESIZE 20
REPHEADER CENTER 'FINE DETAIL' SKIP 1 CENTER 'National Institute Of Science and Technology' SKIP 1 CENTER 'Pallur Hills,Berhampur-761008'
REPFOOTER CENTER RIGHT 'PAGE NO:-'SQL.PNO
BREAK ON LFFINETYPE
COMPUTE SUM OF LFFINEAMT 'TOTAL FINE' ON LFFINETYPE
COLUMN LFFINEAMT HEADING 'FINE AMOUNT'


SELECT LUUSERNAME,BKINDEXNUM,TITITLE,TO_CHAR(BSBOOKTRANSDATE,'MON') FROM LIBBOOKTRANS JOIN LIBUSERS USING (LUUSERID) JOIN LIBTITLES USING(TITITLEID) WHERE TO_CHAR(BSBOOKTRANSDATE,'MON') IN (SELECT TO_CHAR(BSBOOKTRANSDATE,'MON') FROM LIBBOOKTRANS GROUP BY TITITLEID,TO_CHAR(BSBOOKTRANSDATE,'MON') HAVING COUNT(TITITLEID)=(SELECT MIN(COUNT(TITITLEID)) FROM LIBBOOKTRANS GROUP BY TITITLEID,TO_CHAR(BSBOOKTRANSDATE,'MON')));

CLEAR COMPUTE
CLEAR COLUMN 
CLEAR BREAK
TTITLE OFF
REPFOOTER OFF
REPHEADER OFF 