SET LINESIZE 90
SET PAGESIZE 20
REPHEADER CENTER 'FINE DETAIL' SKIP 1 CENTER 'National Institute Of Science and Technology' SKIP 1 CENTER 'Pallur Hills,Berhampur-761008'
REPFOOTER CENTER RIGHT 'PAGE NO:-'SQL.PNO
BREAK ON LFFINETYPE
COMPUTE SUM OF LFFINEAMT 'TOTAL FINE' ON LFFINETYPE
COLUMN LFFINEAMT HEADING 'FINE AMOUNT'

SELECT TITITLE,TOPICNAME,SUBJECTNAME FROM LIBTITLES JOIN LIBSUBJECTS USING (SUBJECTID) JOIN LIBTOPICS USING (TOPICID) WHERE TITITLEID=(SELECT TITITLEID FROM LIBBOOKTRANS GROUP BY TITITLEID HAVING COUNT(TITITLEID)=(SELECT MAX(COUNT(TITITLEID)) FROM LIBBOOKTRANS GROUP BY TITITLEID));


CLEAR COMPUTE
CLEAR COLUMN 
CLEAR BREAK
TTITLE OFF
REPFOOTER OFF
REPHEADER OFF 


