SET LINESIZE 90
SET PAGESIZE 20
REPHEADER CENTER 'FINE DETAIL' SKIP 1 CENTER 'National Institute Of Science and Technology' SKIP 1 CENTER 'Pallur Hills,Berhampur-761008'
REPFOOTER CENTER RIGHT 'PAGE NO:-'SQL.PNO
BREAK ON LFFINETYPE
COMPUTE SUM OF LFFINEAMT 'TOTAL FINE' ON LFFINETYPE
COLUMN LFFINEAMT HEADING 'FINE AMOUNT'

SELECT L.BKINDEXNUM,TITITLE,TOPICNAME,BSBOOKSTATUS FROM libbooks JOIN LIBTITLES USING(TITITLEID) JOIN LIBTOPICS USING (TOPICID) JOIN LIBBOOKSTATUS L USING(TITITLEID) WHERE BSBOOKSTATUS='IS' group by L.BKINDEXNUM,TITITLE,TOPICNAME,BSBOOKSTATUS having count(tititle)=(SELECT MAX(COUNT(TITITLE)) FROM libbooks JOIN LIBTITLES USING(TITITLEID) JOIN LIBTOPICS USING (TOPICID) JOIN LIBBOOKSTATUS L USING(TITITLEID) WHERE BSBOOKSTATUS='RE' GROUP BY l.BKINDEXNUM,TITITLE,TOPICNAME,BSBOOKSTATUS);


CLEAR COMPUTE
CLEAR COLUMN 
CLEAR BREAK
TTITLE OFF
REPFOOTER OFF
REPHEADER OFF 



